In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split , GridSearchCV, TimeSeriesSplit,RandomizedSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('train.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)
df.sort_index(inplace=True)
df.drop(['Store', 'Dept'],axis=1,inplace=True)
df = df.groupby(df.index).agg({'Weekly_Sales': 'sum', 'IsHoliday': 'max'})
df.rename(columns={'Weekly_Sales': 'all_store_Weekly_Sales', 'IsHoliday': 'IsHoliday'}, inplace=True)
df.head()

            all_store_Weekly_Sales  IsHoliday
Date
2010-02-05             49750740.50      False
2010-02-12             48336677.63       True
2010-02-19             48276993.78      False
2010-02-26             43968571.13      False
2010-03-05             46871470.30      False

In [4]:
df['lag1'] = df['all_store_Weekly_Sales'].shift(1)

df['lag2'] = df['all_store_Weekly_Sales'].shift(2)

df['lag3'] = df['all_store_Weekly_Sales'].shift(3)

df['lag4'] = df['all_store_Weekly_Sales'].shift(4)

df['lag5'] = df['all_store_Weekly_Sales'].shift(5)

df['lag6'] = df['all_store_Weekly_Sales'].shift(6)

df['lag7'] = df['all_store_Weekly_Sales'].shift(7)

df['month'] = df.index.month

df['week'] = (df.index.day - 1) // 7 + 1

df['scales_change'] = df['all_store_Weekly_Sales'].pct_change().shift(1) # velocity in sales growth

df['Pre_Holiday_Week'] =  df['IsHoliday'].shift(-1).astype(bool)

df['moving_avg'] = df['all_store_Weekly_Sales'].rolling(window=4).mean()

df['moving_median'] = df['all_store_Weekly_Sales'].rolling(window=4).median()

df['moving_std'] = df['all_store_Weekly_Sales'].rolling(window=4).std()

df['moving_max'] = df['all_store_Weekly_Sales'].rolling(window=4).max()

df['moving_min'] = df['all_store_Weekly_Sales'].shift(1).rolling(window=4).mean()

df['moving_sum'] = df['all_store_Weekly_Sales'].rolling(window=4).sum()

In [5]:
df.columns

Index(['all_store_Weekly_Sales', 'IsHoliday', 'lag1', 'lag2', 'lag3', 'lag4',
       'lag5', 'lag6', 'lag7', 'month', 'week', 'scales_change',
       'Pre_Holiday_Week', 'moving_avg', 'moving_median', 'moving_std',
       'moving_max', 'moving_min', 'moving_sum'],
      dtype='object')

In [6]:
df.dropna(inplace=True)

df.head()

,all_store_Weekly_Sales,IsHoliday,lag1,lag2,lag3,lag4,lag5,lag6,lag7,month,week,scales_change,Pre_Holiday_Week,moving_avg,moving_median,moving_std,moving_max,moving_min,moving_sum
Date,,,,,,,,,,,,,,,,,,,
2010-03-26,44133961.05,False,44988974.64,45925396.51,46871470.30,43968571.13,48276993.78,48336677.63,49750740.50,3,4,-0.020390,False,4.547995e+07,4.545719e+07,1.181453e+06,46871470.30,4.543860e+07,1.819198e+08
2010-04-02,50423831.26,False,44133961.05,44988974.64,45925396.51,46871470.30,43968571.13,48276993.78,48336677.63,4,1,-0.019005,False,4.636804e+07,4.545719e+07,2.801089e+06,50423831.26,4.547995e+07,1.854722e+08
2010-04-09,47365290.44,False,50423831.26,44133961.05,44988974.64,45925396.51,46871470.30,43968571.13,48276993.78,4,2,0.142518,False,4.672801e+07,4.617713e+07,2.817715e+06,50423831.26,4.636804e+07,1.869121e+08
2010-04-16,45183667.08,False,47365290.44,50423831.26,44133961.05,44988974.64,45925396.51,46871470.30,43968571.13,4,3,-0.060657,False,4.677669e+07,4.627448e+07,2.779078e+06,50423831.26,4.672801e+07,1.871067e+08
2010-04-23,44734452.56,False,45183667.08,47365290.44,50423831.26,44133961.05,44988974.64,45925396.51,46871470.30,4,4,-0.046060,False,4.692681e+07,4.627448e+07,2.599128e+06,50423831.26,4.677669e+07,1.877072e+08

In [7]:
df.shape

(136, 19)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 136 entries, 2010-03-26 to 2012-10-26
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   all_store_Weekly_Sales  136 non-null    float64
 1   IsHoliday               136 non-null    bool
 2   lag1                    136 non-null    float64
 3   lag2                    136 non-null    float64
 4   lag3                    136 non-null    float64
 5   lag4                    136 non-null    float64
 6   lag5                    136 non-null    float64
 7   lag6                    136 non-null    float64
 8   lag7                    136 non-null    float64
 9   month                   136 non-null    int32
 10  week                    136 non-null    int32
 11  scales_change           136 non-null    float64
 12  Pre_Holiday_Week        136 non-null    bool
 13  moving_avg              136 non-null    float64
 14  moving_median           136 non-null    float64
 15  moving_std              136 non-null    float64
 16  moving_max              136 non-null    float64
 17  moving_min              136 non-null    float64
 18  moving_sum              136 non-null    float64
dtypes: bool(2), float64(15), int32(2)
memory usage: 18.3 KB

In [9]:
x = df.drop('all_store_Weekly_Sales',axis=1)
y = df['all_store_Weekly_Sales']

x_train = x[:-12]
x_test = x[-12:]

y_train = y[:-12]
y_test = y[-12:]

In [10]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(124, 18)
(12, 18)
(124,)
(12,)

In [11]:
par_xgb ={
    'learning_rate': [0.2,0.1],
    'max_depth': [4,3],
    'n_estimators': [500, 400],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 2],
    'reg_lambda': [1, 10]
}

xgb = XGBRegressor(objective='reg:squarederror', random_state=42)
grid_xgb = GridSearchCV(xgb, par_xgb, cv=5, n_jobs=-1, verbose=1,scoring='neg_root_mean_squared_error')
grid_xgb.fit(x_train, y_train)

Fitting 5 folds for each of 128 candidates, totalling 640 fits

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None...
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.8, 1.0],
                         'learning_rate': [0.2, 0.1], 'max_depth': [4, 3],
                         'min_child_weight': [1, 2], 'n_estimators': [500, 400],
                         'reg_lambda': [1, 10], 'subsample': [0.8, 1.0]},
             scoring='neg_root_mean_squared_error', verbose=1)

In [12]:
print(grid_xgb.best_params_)
print(grid_xgb.best_score_)

{'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 2, 'n_estimators': 500, 'reg_lambda': 10, 'subsample': 0.8}
-2221513.391259258

In [13]:

feat_imp = pd.Series(grid_xgb.best_estimator_.feature_importances_, index=x_train.columns)

print(feat_imp.sort_values(ascending=False))

best_feature = feat_imp[feat_imp > 0.02].index

print(best_feature)

month               0.465194
moving_avg          0.105342
moving_sum          0.066958
week                0.054094
lag5                0.052725
moving_std          0.047812
IsHoliday           0.046547
lag1                0.042632
moving_median       0.023026
moving_max          0.022509
lag7                0.016375
scales_change       0.013160
lag3                0.010222
moving_min          0.009593
lag4                0.009064
lag2                0.008185
lag6                0.005926
Pre_Holiday_Week    0.000636
dtype: float32
Index(['IsHoliday', 'lag1', 'lag5', 'month', 'week', 'moving_avg',
       'moving_median', 'moving_std', 'moving_max', 'moving_sum'],
      dtype='object')

In [14]:
y_pred = grid_xgb.predict(x_test)                               

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print('RMSE:', rmse)
print('R2:', r2)

RMSE: 929117.2578325291
R2: 0.6111154840226525

In [15]:
x  = df[best_feature]
y = df['all_store_Weekly_Sales']

x_train = x[:-12]
x_test = x[-12:]

y_train = y[:-12]
y_test = y[-12:]

In [17]:
import optuna

c:\Users\kumar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [18]:
def optimise_xgb(trial):
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    max_depth = trial.suggest_int('max_depth', 3, 9)
    n_estimators = trial.suggest_int('n_estimators', 100, 800)
    subsample = trial.suggest_float('subsample', 0.5, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.2, 1.0)
    colsample_bylevel = trial.suggest_float('colsample_bylevel', 0.2, 1.0)
    min_child_weight = trial.suggest_int('min_child_weight', 2, 9)
    gamma = trial.suggest_float('gamma', 0, 9)
    reg_lambda = trial.suggest_float('reg_lambda', 0, 9)
    reg_alpha = trial.suggest_float('reg_alpha', 0, 9)


    model = XGBRegressor(
        learning_rate=learning_rate,
        max_depth=max_depth,
        n_estimators=n_estimators,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        colsample_bylevel=colsample_bylevel,
        min_child_weight=min_child_weight,
        gamma=gamma,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        random_state=42
    )

    model.fit(x_train, y_train)

    tscv = TimeSeriesSplit(n_splits=5)

    score = cross_val_score(model, x_train, y_train, cv=tscv, scoring='neg_root_mean_squared_error').mean()

    return score

In [19]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(optimise_xgb, n_trials=30)

[I 2026-05-07 02:44:22,512] A new study created in memory with name: no-name-30fc1d06-76f1-4e3c-b841-f78ce17c6213
[I 2026-05-07 02:44:24,710] Trial 0 finished with value: -5301552.876618385 and parameters: {'learning_rate': 0.14734827442950585, 'max_depth': 8, 'n_estimators': 568, 'subsample': 0.7698686102592363, 'colsample_bytree': 0.23338827742497453, 'colsample_bylevel': 0.47755247483849816, 'min_child_weight': 9, 'gamma': 3.0269410350975967, 'reg_lambda': 5.453695400742728, 'reg_alpha': 3.2172822283110944}. Best is trial 0 with value: -5301552.876618385.
[I 2026-05-07 02:44:26,202] Trial 1 finished with value: -3905727.8252353496 and parameters: {'learning_rate': 0.0993081910056582, 'max_depth': 4, 'n_estimators': 599, 'subsample': 0.8954474027203232, 'colsample_bytree': 0.6883506466354494, 'colsample_bylevel': 0.7858537312350473, 'min_child_weight': 5, 'gamma': 5.36401307573799, 'reg_lambda': 4.677029776985244, 'reg_alpha': 1.8240605304157267}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:26,929] Trial 2 finished with value: -4544434.502108324 and parameters: {'learning_rate': 0.14561672998228783, 'max_depth': 4, 'n_estimators': 247, 'subsample': 0.9830961074695419, 'colsample_bytree': 0.65356970032905, 'colsample_bylevel': 0.37190119711175057, 'min_child_weight': 4, 'gamma': 3.2597097488372966, 'reg_lambda': 0.753326137315332, 'reg_alpha': 8.94999376828506}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:28,097] Trial 3 finished with value: -4565239.319507166 and parameters: {'learning_rate': 0.10556824421428875, 'max_depth': 4, 'n_estimators': 438, 'subsample': 0.6079401738931804, 'colsample_bytree': 0.26662652455797486, 'colsample_bylevel': 0.9417718785049929, 'min_child_weight': 5, 'gamma': 7.265969397128539, 'reg_lambda': 6.46135204685457, 'reg_alpha': 0.37538928777371827}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:29,625] Trial 4 finished with value: -4583470.293167541 and parameters: {'learning_rate': 0.2904422582049249, 'max_depth': 5, 'n_estimators': 507, 'subsample': 0.9979622986059147, 'colsample_bytree': 0.34465977791336233, 'colsample_bylevel': 0.6363568919655377, 'min_child_weight': 4, 'gamma': 5.576335323189841, 'reg_lambda': 7.596048954985049, 'reg_alpha': 6.100652757184995}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:29,990] Trial 5 finished with value: -4263404.349487575 and parameters: {'learning_rate': 0.03813044825649102, 'max_depth': 5, 'n_estimators': 119, 'subsample': 0.9738587923577541, 'colsample_bytree': 0.40941733984080486, 'colsample_bylevel': 0.4288398200314363, 'min_child_weight': 2, 'gamma': 1.9190506427881329, 'reg_lambda': 7.090084592583716, 'reg_alpha': 5.642497706216573}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:31,771] Trial 6 finished with value: -4200852.947415954 and parameters: {'learning_rate': 0.11122300838230464, 'max_depth': 7, 'n_estimators': 552, 'subsample': 0.6319581224308742, 'colsample_bytree': 0.807006387206163, 'colsample_bylevel': 0.883533338917817, 'min_child_weight': 5, 'gamma': 2.213346059342987, 'reg_lambda': 7.323795435054219, 'reg_alpha': 0.31549318614935384}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:33,288] Trial 7 finished with value: -4614962.101816414 and parameters: {'learning_rate': 0.1543103242315992, 'max_depth': 8, 'n_estimators': 672, 'subsample': 0.9200844938073551, 'colsample_bytree': 0.2209299537573843, 'colsample_bylevel': 0.6027803515818124, 'min_child_weight': 6, 'gamma': 6.770361325177573, 'reg_lambda': 7.729777181755731, 'reg_alpha': 7.0332573917710155}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:33,926] Trial 8 finished with value: -4810926.290106917 and parameters: {'learning_rate': 0.2549155214439069, 'max_depth': 4, 'n_estimators': 346, 'subsample': 0.7729551171841826, 'colsample_bytree': 0.23855310806523866, 'colsample_bylevel': 0.44050060064580143, 'min_child_weight': 6, 'gamma': 5.730867800100053, 'reg_lambda': 4.421481655041124, 'reg_alpha': 0.24269290536436428}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:35,070] Trial 9 finished with value: -4805251.610873072 and parameters: {'learning_rate': 0.10738392069985686, 'max_depth': 9, 'n_estimators': 616, 'subsample': 0.876066821950927, 'colsample_bytree': 0.966722406040011, 'colsample_bylevel': 0.431081558730724, 'min_child_weight': 8, 'gamma': 5.041959897538603, 'reg_lambda': 8.163023494035222, 'reg_alpha': 2.4309866695552675}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:36,263] Trial 10 finished with value: -4146318.7889869125 and parameters: {'learning_rate': 0.033471085158877534, 'max_depth': 3, 'n_estimators': 752, 'subsample': 0.5092535363551616, 'colsample_bytree': 0.5470964571591739, 'colsample_bylevel': 0.7631221777794497, 'min_child_weight': 2, 'gamma': 0.7242523744157654, 'reg_lambda': 2.7716104369045054, 'reg_alpha': 2.569898498016772}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:37,457] Trial 11 finished with value: -4111424.2190301777 and parameters: {'learning_rate': 0.028647736494369136, 'max_depth': 3, 'n_estimators': 794, 'subsample': 0.5051865559269497, 'colsample_bytree': 0.5518289072220598, 'colsample_bylevel': 0.7698098463449559, 'min_child_weight': 2, 'gamma': 0.1801249107095675, 'reg_lambda': 2.656769343415059, 'reg_alpha': 2.498730859702242}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:38,766] Trial 12 finished with value: -4061581.265643335 and parameters: {'learning_rate': 0.05290301978602996, 'max_depth': 3, 'n_estimators': 785, 'subsample': 0.8426193119523944, 'colsample_bytree': 0.6539166859572353, 'colsample_bylevel': 0.20820946393943524, 'min_child_weight': 3, 'gamma': 3.9973165362180727, 'reg_lambda': 3.169459456293122, 'reg_alpha': 3.804936187720661}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:40,155] Trial 13 finished with value: -4243203.767801727 and parameters: {'learning_rate': 0.0722719579648453, 'max_depth': 6, 'n_estimators': 702, 'subsample': 0.8487819567422387, 'colsample_bytree': 0.7082538816477082, 'colsample_bylevel': 0.2441224353335414, 'min_child_weight': 4, 'gamma': 8.646813369975003, 'reg_lambda': 3.611425431846773, 'reg_alpha': 4.107170975292786}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:41,209] Trial 14 finished with value: -4270778.57972076 and parameters: {'learning_rate': 0.200813376641987, 'max_depth': 3, 'n_estimators': 662, 'subsample': 0.8308889764968209, 'colsample_bytree': 0.8278200637205978, 'colsample_bylevel': 0.2712387705911037, 'min_child_weight': 3, 'gamma': 4.1957933204420454, 'reg_lambda': 0.9142225605948755, 'reg_alpha': 4.139632984752865}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:42,309] Trial 15 finished with value: -4527364.41569384 and parameters: {'learning_rate': 0.07339508841587701, 'max_depth': 5, 'n_estimators': 431, 'subsample': 0.7022739901095901, 'colsample_bytree': 0.4667693813884704, 'colsample_bylevel': 0.7288669113493524, 'min_child_weight': 7, 'gamma': 3.7558553398304766, 'reg_lambda': 5.654660110553853, 'reg_alpha': 1.470966733765004}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:44,252] Trial 16 finished with value: -4562679.501674725 and parameters: {'learning_rate': 0.20143270747850278, 'max_depth': 6, 'n_estimators': 799, 'subsample': 0.9116741869169777, 'colsample_bytree': 0.7541045793808836, 'colsample_bylevel': 0.8484247935188266, 'min_child_weight': 3, 'gamma': 6.571841272184162, 'reg_lambda': 1.9664669833561765, 'reg_alpha': 5.026388398411259}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:45,700] Trial 17 finished with value: -4570541.110331167 and parameters: {'learning_rate': 0.06927623701094456, 'max_depth': 4, 'n_estimators': 717, 'subsample': 0.8141730666201217, 'colsample_bytree': 0.9207913932564342, 'colsample_bylevel': 0.9840730763488947, 'min_child_weight': 7, 'gamma': 8.042341986145237, 'reg_lambda': 4.405246768321563, 'reg_alpha': 1.5642996665535367}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:46,891] Trial 18 finished with value: -4236863.831633949 and parameters: {'learning_rate': 0.19507993709266674, 'max_depth': 3, 'n_estimators': 584, 'subsample': 0.9142789502318509, 'colsample_bytree': 0.6232245870321613, 'colsample_bylevel': 0.5648563218867432, 'min_child_weight': 3, 'gamma': 4.688823093190992, 'reg_lambda': 8.86462068573153, 'reg_alpha': 3.4057674041805743}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:47,885] Trial 19 finished with value: -4319731.342420916 and parameters: {'learning_rate': 0.06056884636549419, 'max_depth': 6, 'n_estimators': 500, 'subsample': 0.707200581554139, 'colsample_bytree': 0.8718423580772366, 'colsample_bylevel': 0.20295545667763548, 'min_child_weight': 5, 'gamma': 5.9661808948502575, 'reg_lambda': 3.570934319884044, 'reg_alpha': 7.433992663863246}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:48,422] Trial 20 finished with value: -4315228.224336608 and parameters: {'learning_rate': 0.01268689789603232, 'max_depth': 4, 'n_estimators': 318, 'subsample': 0.7168145106081324, 'colsample_bytree': 0.6888382973352128, 'colsample_bylevel': 0.6627158820403481, 'min_child_weight': 4, 'gamma': 2.1208231387679346, 'reg_lambda': 5.749845732923503, 'reg_alpha': 1.4411803099740301}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:49,736] Trial 21 finished with value: -4107472.995964028 and parameters: {'learning_rate': 0.015764678654519214, 'max_depth': 3, 'n_estimators': 798, 'subsample': 0.5118119191273688, 'colsample_bytree': 0.5584161630828601, 'colsample_bylevel': 0.7842179264623224, 'min_child_weight': 2, 'gamma': 0.14226372820237643, 'reg_lambda': 1.9743197052227939, 'reg_alpha': 2.355695238026682}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:50,697] Trial 22 finished with value: -4110115.571490889 and parameters: {'learning_rate': 0.012159171586624232, 'max_depth': 3, 'n_estimators': 641, 'subsample': 0.5739033834069841, 'colsample_bytree': 0.5436031212931892, 'colsample_bylevel': 0.836612335634931, 'min_child_weight': 3, 'gamma': 1.1140563764243083, 'reg_lambda': 1.7549475369349576, 'reg_alpha': 3.473885716424766}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:51,957] Trial 23 finished with value: -4111526.588721479 and parameters: {'learning_rate': 0.05210137271585693, 'max_depth': 3, 'n_estimators': 737, 'subsample': 0.8075451683803282, 'colsample_bytree': 0.4836790808873067, 'colsample_bylevel': 0.5315637923047003, 'min_child_weight': 2, 'gamma': 2.873539413005868, 'reg_lambda': 3.512114199166433, 'reg_alpha': 1.9015621014253443}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:53,753] Trial 24 finished with value: -4482907.182132048 and parameters: {'learning_rate': 0.0917216731000855, 'max_depth': 5, 'n_estimators': 796, 'subsample': 0.8880430301203823, 'colsample_bytree': 0.7625366146617649, 'colsample_bylevel': 0.6967616062222801, 'min_child_weight': 3, 'gamma': 1.3575442445674584, 'reg_lambda': 1.6660050184043098, 'reg_alpha': 4.720969700841842}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:55,530] Trial 25 finished with value: -4166765.3172270632 and parameters: {'learning_rate': 0.13149201045063136, 'max_depth': 4, 'n_estimators': 740, 'subsample': 0.9484704661468358, 'colsample_bytree': 0.6059617926917619, 'colsample_bylevel': 0.3359017012405308, 'min_child_weight': 2, 'gamma': 4.169166915848763, 'reg_lambda': 0.09413910268364512, 'reg_alpha': 2.9895561905108545}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:56,724] Trial 26 finished with value: -4102121.3499949304 and parameters: {'learning_rate': 0.08260754068144223, 'max_depth': 3, 'n_estimators': 620, 'subsample': 0.669434470858181, 'colsample_bytree': 0.6933639134731876, 'colsample_bylevel': 0.8155991944000959, 'min_child_weight': 4, 'gamma': 5.034390073811199, 'reg_lambda': 2.690751686003302, 'reg_alpha': 1.155421620590352}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:57,527] Trial 27 finished with value: -4084811.6645927974 and parameters: {'learning_rate': 0.12509568181570843, 'max_depth': 4, 'n_estimators': 490, 'subsample': 0.659309503095556, 'colsample_bytree': 0.7660765494635057, 'colsample_bylevel': 0.9067272697396068, 'min_child_weight': 5, 'gamma': 5.192927132072327, 'reg_lambda': 4.765374928396966, 'reg_alpha': 0.9689425187089152}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:58,620] Trial 28 finished with value: -4017564.7693153145 and parameters: {'learning_rate': 0.17684109050640173, 'max_depth': 5, 'n_estimators': 488, 'subsample': 0.7395597915829744, 'colsample_bytree': 0.7698970079766405, 'colsample_bylevel': 0.8925690040326385, 'min_child_weight': 6, 'gamma': 3.5951938702396644, 'reg_lambda': 4.886524576537362, 'reg_alpha': 0.023917540234869472}. Best is trial 1 with value: -3905727.8252353496.
[I 2026-05-07 02:44:59,363] Trial 29 finished with value: -4371593.225288484 and parameters: {'learning_rate': 0.16940948742531528, 'max_depth': 7, 'n_estimators': 375, 'subsample': 0.7722944310027925, 'colsample_bytree': 0.8460451528241453, 'colsample_bylevel': 0.9694973092157967, 'min_child_weight': 7, 'gamma': 3.3910788508968, 'reg_lambda': 5.04981074645665, 'reg_alpha': 0.03405852181415625}. Best is trial 1 with value: -3905727.8252353496.

In [20]:
print(study.best_params)
print(study.best_value)

{'learning_rate': 0.0993081910056582, 'max_depth': 4, 'n_estimators': 599, 'subsample': 0.8954474027203232, 'colsample_bytree': 0.6883506466354494, 'colsample_bylevel': 0.7858537312350473, 'min_child_weight': 5, 'gamma': 5.36401307573799, 'reg_lambda': 4.677029776985244, 'reg_alpha': 1.8240605304157267}
-3905727.8252353496

In [21]:

best_params = study.best_params

best_model = XGBRegressor(**best_params, random_state=42)

best_model.fit(x_train, y_train)

y_pred = best_model.predict(x_test)                               

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print('RMSE:', rmse)
print('R2:', r2)

RMSE: 1176890.1850741915
R2: 0.3760475713402692

In [44]:
def optimise_xgb(trial):
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.9),
        'max_depth': trial.suggest_int('max_depth', 2, 9),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.2, 1.0),
        'gamma': trial.suggest_int('gamma', 2, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 2, 9),
        'reg_lambda': trial.suggest_int('reg_lambda', 0, 9), 
        'reg_alpha': trial.suggest_int('reg_alpha', 0, 9)
    }

    model = XGBRegressor(**params, random_state=42)
    
    tscv = TimeSeriesSplit(n_splits=5)
    
    score = cross_val_score(model, x_train, y_train, cv=tscv, scoring='neg_root_mean_squared_error').mean()
    return score

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(optimise_xgb, n_trials=25)

[I 2026-05-07 02:51:04,667] A new study created in memory with name: no-name-e0350b08-19f7-41c9-b127-9b9b32192a8b
[I 2026-05-07 02:51:06,156] Trial 0 finished with value: -5805929.235589166 and parameters: {'learning_rate': 0.23572685176684238, 'max_depth': 6, 'n_estimators': 447, 'subsample': 0.33015348027815705, 'gamma': 3, 'min_child_weight': 8, 'reg_lambda': 5, 'reg_alpha': 9}. Best is trial 0 with value: -5805929.235589166.
[I 2026-05-07 02:51:08,156] Trial 1 finished with value: -4506117.305321024 and parameters: {'learning_rate': 0.010687166614376154, 'max_depth': 6, 'n_estimators': 957, 'subsample': 0.5744012275570651, 'gamma': 4, 'min_child_weight': 7, 'reg_lambda': 0, 'reg_alpha': 3}. Best is trial 1 with value: -4506117.305321024.
[I 2026-05-07 02:51:09,304] Trial 2 finished with value: -4567430.06560903 and parameters: {'learning_rate': 0.08232267311666025, 'max_depth': 9, 'n_estimators': 426, 'subsample': 0.7407304818101972, 'gamma': 5, 'min_child_weight': 3, 'reg_lambda': 1, 'reg_alpha': 3}. Best is trial 1 with value: -4506117.305321024.
[I 2026-05-07 02:51:10,378] Trial 3 finished with value: -7551231.776920432 and parameters: {'learning_rate': 0.840745072777306, 'max_depth': 2, 'n_estimators': 828, 'subsample': 0.5163488141634855, 'gamma': 3, 'min_child_weight': 9, 'reg_lambda': 5, 'reg_alpha': 2}. Best is trial 1 with value: -4506117.305321024.
[I 2026-05-07 02:51:11,023] Trial 4 finished with value: -4419935.725724893 and parameters: {'learning_rate': 0.20326787991714707, 'max_depth': 8, 'n_estimators': 275, 'subsample': 0.9230773193075374, 'gamma': 3, 'min_child_weight': 4, 'reg_lambda': 0, 'reg_alpha': 6}. Best is trial 4 with value: -4419935.725724893.
[I 2026-05-07 02:51:12,779] Trial 5 finished with value: -4770127.192607356 and parameters: {'learning_rate': 0.14413715893610832, 'max_depth': 6, 'n_estimators': 995, 'subsample': 0.735057111982234, 'gamma': 3, 'min_child_weight': 7, 'reg_lambda': 3, 'reg_alpha': 6}. Best is trial 4 with value: -4419935.725724893.
[I 2026-05-07 02:51:13,133] Trial 6 finished with value: -4331289.836881621 and parameters: {'learning_rate': 0.5507379222658021, 'max_depth': 4, 'n_estimators': 210, 'subsample': 0.7826777739848121, 'gamma': 2, 'min_child_weight': 2, 'reg_lambda': 5, 'reg_alpha': 0}. Best is trial 6 with value: -4331289.836881621.
[I 2026-05-07 02:51:13,685] Trial 7 finished with value: -7498197.031276181 and parameters: {'learning_rate': 0.675608172101318, 'max_depth': 5, 'n_estimators': 604, 'subsample': 0.3270298088366992, 'gamma': 4, 'min_child_weight': 7, 'reg_lambda': 6, 'reg_alpha': 7}. Best is trial 6 with value: -4331289.836881621.
[I 2026-05-07 02:51:15,243] Trial 8 finished with value: -4885900.006843083 and parameters: {'learning_rate': 0.5712481717419776, 'max_depth': 4, 'n_estimators': 868, 'subsample': 0.9719533873916932, 'gamma': 3, 'min_child_weight': 8, 'reg_lambda': 4, 'reg_alpha': 1}. Best is trial 6 with value: -4331289.836881621.
[I 2026-05-07 02:51:16,632] Trial 9 finished with value: -4649450.05780129 and parameters: {'learning_rate': 0.3278233781959715, 'max_depth': 4, 'n_estimators': 724, 'subsample': 0.4069904246847464, 'gamma': 6, 'min_child_weight': 2, 'reg_lambda': 4, 'reg_alpha': 9}. Best is trial 6 with value: -4331289.836881621.
[I 2026-05-07 02:51:16,929] Trial 10 finished with value: -4489247.569360639 and parameters: {'learning_rate': 0.4273023834778181, 'max_depth': 2, 'n_estimators': 128, 'subsample': 0.7746538704692173, 'gamma': 8, 'min_child_weight': 5, 'reg_lambda': 9, 'reg_alpha': 0}. Best is trial 6 with value: -4331289.836881621.
[I 2026-05-07 02:51:17,364] Trial 11 finished with value: -3876058.7038208223 and parameters: {'learning_rate': 0.5289387683777043, 'max_depth': 9, 'n_estimators': 129, 'subsample': 0.9894372630500964, 'gamma': 2, 'min_child_weight': 4, 'reg_lambda': 7, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:17,683] Trial 12 finished with value: -4337427.848825644 and parameters: {'learning_rate': 0.57659782252352, 'max_depth': 8, 'n_estimators': 127, 'subsample': 0.8318858233360941, 'gamma': 2, 'min_child_weight': 2, 'reg_lambda': 7, 'reg_alpha': 4}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:18,125] Trial 13 finished with value: -4612348.683592259 and parameters: {'learning_rate': 0.7116857651929049, 'max_depth': 4, 'n_estimators': 273, 'subsample': 0.9992697911908939, 'gamma': 9, 'min_child_weight': 4, 'reg_lambda': 9, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:18,994] Trial 14 finished with value: -4411527.082675857 and parameters: {'learning_rate': 0.4247646854563787, 'max_depth': 9, 'n_estimators': 275, 'subsample': 0.8641822728438655, 'gamma': 2, 'min_child_weight': 3, 'reg_lambda': 7, 'reg_alpha': 0}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:19,339] Trial 15 finished with value: -4456919.663959665 and parameters: {'learning_rate': 0.5490919126237261, 'max_depth': 7, 'n_estimators': 108, 'subsample': 0.6581275137261297, 'gamma': 6, 'min_child_weight': 4, 'reg_lambda': 7, 'reg_alpha': 7}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:19,814] Trial 16 finished with value: -11579950.998374011 and parameters: {'learning_rate': 0.8250682198763069, 'max_depth': 3, 'n_estimators': 399, 'subsample': 0.20218131434884373, 'gamma': 7, 'min_child_weight': 5, 'reg_lambda': 2, 'reg_alpha': 4}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:20,376] Trial 17 finished with value: -4408332.472248913 and parameters: {'learning_rate': 0.6937761112616131, 'max_depth': 5, 'n_estimators': 216, 'subsample': 0.8522264739531116, 'gamma': 2, 'min_child_weight': 3, 'reg_lambda': 8, 'reg_alpha': 2}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:21,450] Trial 18 finished with value: -4258850.953269387 and parameters: {'learning_rate': 0.3269798090772595, 'max_depth': 7, 'n_estimators': 561, 'subsample': 0.642768615368303, 'gamma': 5, 'min_child_weight': 2, 'reg_lambda': 6, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:22,429] Trial 19 finished with value: -4278436.010200391 and parameters: {'learning_rate': 0.3560227635922375, 'max_depth': 8, 'n_estimators': 575, 'subsample': 0.6460712410903483, 'gamma': 5, 'min_child_weight': 5, 'reg_lambda': 6, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:24,575] Trial 20 finished with value: -5214408.589537149 and parameters: {'learning_rate': 0.3284410001321785, 'max_depth': 7, 'n_estimators': 665, 'subsample': 0.5197070371506761, 'gamma': 7, 'min_child_weight': 6, 'reg_lambda': 8, 'reg_alpha': 7}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:26,084] Trial 21 finished with value: -4375905.097022501 and parameters: {'learning_rate': 0.3614090868041325, 'max_depth': 8, 'n_estimators': 545, 'subsample': 0.6569115419453542, 'gamma': 5, 'min_child_weight': 5, 'reg_lambda': 6, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:27,158] Trial 22 finished with value: -4656569.521084178 and parameters: {'learning_rate': 0.2689185721125829, 'max_depth': 9, 'n_estimators': 515, 'subsample': 0.6644044092134116, 'gamma': 4, 'min_child_weight': 6, 'reg_lambda': 6, 'reg_alpha': 6}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:28,027] Trial 23 finished with value: -4913850.178470522 and parameters: {'learning_rate': 0.48074775382730284, 'max_depth': 7, 'n_estimators': 705, 'subsample': 0.44006016574119655, 'gamma': 5, 'min_child_weight': 4, 'reg_lambda': 8, 'reg_alpha': 5}. Best is trial 11 with value: -3876058.7038208223.
[I 2026-05-07 02:51:29,190] Trial 24 finished with value: -4397331.858779199 and parameters: {'learning_rate': 0.48143784386028493, 'max_depth': 8, 'n_estimators': 629, 'subsample': 0.5790476574204639, 'gamma': 7, 'min_child_weight': 3, 'reg_lambda': 6, 'reg_alpha': 4}. Best is trial 11 with value: -3876058.7038208223.

In [45]:
print(study.best_params)
print(study.best_value)

{'learning_rate': 0.5289387683777043, 'max_depth': 9, 'n_estimators': 129, 'subsample': 0.9894372630500964, 'gamma': 2, 'min_child_weight': 4, 'reg_lambda': 7, 'reg_alpha': 5}
-3876058.7038208223

In [46]:
best_params = study.best_params

best_model = XGBRegressor(**best_params, random_state=42)

best_model.fit(x_train, y_train)

y_pred = best_model.predict(x_test)                               

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print('RMSE:', rmse)
print('R2:', r2)

RMSE: 680108.049436037
R2: 0.7916298868756623

In [47]:
print(study.best_params)

{'learning_rate': 0.5289387683777043, 'max_depth': 9, 'n_estimators': 129, 'subsample': 0.9894372630500964, 'gamma': 2, 'min_child_weight': 4, 'reg_lambda': 7, 'reg_alpha': 5}

{'learning_rate': 0.5289387683777043, 'max_depth': 9, 'n_estimators': 129, 'subsample': 0.9894372630500964, 'gamma': 2, 'min_child_weight': 4, 'reg_lambda': 7, 'reg_alpha': 5}

In [49]:
import joblib   

joblib.dump(best_model, 'xgb_model.pkl')

['xgb_model.pkl']